#!/bin/sh
#
#
# Description:	wrapper of OCF RA FloatingIP, based on RA apache wrapper. 
#		Allocates and deallocates floating IPs on OpenStack. See
#		OCF RA FloatingIP for more information.
#
# Author:	Jorge Rodriguez A.K.A. Tiriel <jorge.rodriguez@forgeservicelab.fi>
# License:	GNU General Public License (GPL)
# Copyright:	(C) 2014 Digile Ltd.
#
# An example usage in /etc/ha.d/haresources: 
#       node1  10.0.0.170 FloatingIP::/etc/opesntack/nova.conf
#

. /etc/ha.d/resource.d//hto-mapfuncs

usage() {
    echo "usage: $0 [config-file-pathname] $LEGAL_ACTIONS"
    exit 1
}

case $# in
  2)	OCF_RESKEY_configfile=$1; export OCF_RESKEY_configfile
	op=$2
	;;
  *)	usage
	;;
esac

OCF_TYPE=FloatingIP
OCF_RESOURCE_INSTANCE=${OCF_TYPE}_$OCF_RESKEY_configfile
export OCF_TYPE OCF_RESOURCE_INSTANCE

ra_execocf $op
